### ISSUE TITLE
Problem with src <script src="../"></script>

### ISSUE THREAD

**Issue by konutis** [joellongie/superCell#2]
I have a problem with the bower_components. Because index.html is in folder public, but bower_components is outside of public folder. If i do this -> <script src='../bower_components/jquery/dist/jquery.js'></script> , it wouldn't work. Error in console -> GET http://localhost:3000/bower_components/jquery/dist/jquery.js . Can anybody help?

**Comment by joellongie** [comment]
Please read the readme.  "Since this is used for my own projects I am currently not accepting public pull requests on this repo. Other then that please feel free to use it however you like."
