### ISSUE TITLE
npm start error...

### ISSUE THREAD

**Issue by chanakairugal** [joellongie/superCell#6]
Why is this happening in the WINDOWS 10 Environment ?
Node V: v4.4.5
NPM V : 3.10.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12

G:\Workspaces\supercell_test>npm start

> superCell@1.0.8 start G:\Workspaces\supercell_test
> NODE_ENV=development gulp

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE
npm ERR! superCell@1.0.8 start: `NODE_ENV=development gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superCell@1.0.8 start script 'NODE_ENV=development gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the superCell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs superCell
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls superCell
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\Workspaces\supercell_test\npm-debug.log

G:\Workspaces\supercell_test>

**Comment by joellongie** [comment]
Windows doesn't support the NODE_ENV variable.  Just use the 'gulp' command instead.  See readme file.

**Comment by chanakairugal** [comment]
Yep i just use that. but thats not gonna generate map files :(
