### ISSUE TITLE
Need to know can we do multiple theme with SuperCell? 

### ISSUE THREAD

**Issue by chanakairugal** [joellongie/superCell#7]
I need to know how to create task that execute multiple theme and component css files when certain file change...

This is how my file structure looks like

http://stackoverflow.com/questions/38283094/is-is-possible-to-do-multiple-theme-css-files-with-gulp-task

**Comment by joellongie** [comment]
I dont understand the question

**Comment by chanakairugal** [comment]
No worries, i just figure it out. actually im creating component library for large scale project. that also contains themes for each and every single client if they want deferant appearance for the component. problem was i need to compile css file that relevent to the sass folder and also them.

as example i have booking widget thats has sass and css file in same folder. also got abc theme that theme file change appearance of the that widget :) so that folder also got css and sass files 

any way we just change the direction of that matter so now we got less complicated environment so this issue not gonna be effected. thanks any way

**Comment by joellongie** [comment]
chanakairugal glad you found a solution that worked for you :)
