### ISSUE TITLE
jshint error - esversion 6 - solution

### ISSUE THREAD

**Issue by ScorpioCoding** [joellongie/superCell#8]
# Issue
I kept on getting jshint errors when reading your gulpfile.js and not just yours my own projects as well.
So I went a searching a came across a simple solution, actually found two.
The issue is the code you use is ES6/2015 and jshint need clarification

# Solution 1
Just add the following at the top of your gulpfile.js
`/*jshint esversion: 6 */`

# Solution 2
So solution 1 is per *.js file you create the tag has to be included - repetitive and thus not good coding practise. So if you have multiple *.js documents.

## Step 1
Add a new file to the root of our project folder 
`.jshintrc`

> dont forget the **dot**
## Step 2
Add the following code to the '.jshintrc' file
`{
    "esversion": 6
}
`

**Comment by joellongie** [comment]
I'm not really supporting this version, will be having a complete rewrite coming soon.
